name: Rename frontend -> docs

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  move:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rename folder
        run: |
          if [ -d "frontend" ]; then
            git mv frontend docs
          fi
      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: rename frontend -> docs" || echo "No changes"
          git push
